require('plugins')
require('lv-globals')
require('lv-utils')
vim.cmd('luafile ~/.config/nvim/lv-settings.lua')
require('lv-autocommands')
require('settings')
require('keymappings')
require('colorscheme')
require('lv-lualine')
require('lv-comment')
require('lv-barbar')
require('lv-dashboard')
require('lv-telescope')
require('lv-nvimtree')
require('lv-treesitter')
require('lv-autopairs')
require('lv-comfortable-motion')
require('lv-i3config')

-- Which Key (Hope to replace with Lua plugin someday)
vim.cmd('source ~/.config/nvim/vimscript/lv-whichkey/init.vim')
vim.cmd('source ~/.config/nvim/vimscript/lv-coc/init.vim')
