require('config.colorscheme')
require('config.maximizer')
require('config.i3_config')
require('config.barbar')
-- require('config.yank_highlight')
require('config.indent_line')
require('config.comfortable_motion')
require('config.telescope')
-- require('config.hardline')
require('config.treesitter')
-- require('config.compe')
require('config.which_key')
-- require('config.saga')
require('config.easy_align')
-- require('config.gv')
require('config.flog')
require('config.vimspector')
require('config.nvimtree')
require('config.colorizer')
require('config.lualine')
require('config.coc')
